# Generated by Django 6.0 on 2026-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True)),
            ],
        ),
    ]
