# Generated by Django 6.0 on 2026-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('disiplina', models.CharField()),
                ('foto', models.ImageField(upload_to='entrenadores/')),
                ('dias', models.CharField(blank=True, help_text='Ej: Lunes,Miercoles y viernes', max_length=150)),
                ('horarios', models.CharField(blank=True, help_text='Ej : 19:00 a 20:30', max_length=150)),
                ('info_adicional', models.CharField(blank=True, help_text='Ej: Todos los niveles / Mixto / Turno tarde', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='0 aparece primero, 1 después, etc.')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para que se vea en la web')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
