# Generated by Django 6.0 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Entrenador',
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='disiplina',
            new_name='disciplina',
        ),
    ]
