# Generated by Django 6.0 on 2026-09-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('responsble', models.CharField(max_length=100)),
                ('telefono_responsable', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('numero_socios', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
