# Generated by Django 6.0 on 2026-09-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='responsble',
            new_name='responsable',
        ),
    ]
