# Generated by Django 6.0 on 2026-09-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_rename_responsble_socio_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
