# Generated by Django 6.0 on 2026-09-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.FileField(upload_to='comprobante/')),
                ('estado', models.CharField(choices=[('Pendiente', 'pendiente'), ('Aprobado', 'aprobado'), ('Rechazado', 'rechazado')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='socios.socio')),
            ],
        ),
    ]
