# Generated by Django 6.0 on 2026-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Descripción o título opcional', max_length=150)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True, help_text='Marcar para que sea visible en la web')),
                ('orden', models.PositiveIntegerField(default=0, help_text='0 aparece primero, luego 1, 2, etc.')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['orden', '-fecha'],
            },
        ),
    ]
